favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    About: /about
    Quotes: /quotes
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/AngryPowman']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['AngryPowman', 'This is a link', 'http://powman.org']
    - ['Demo Links', 'You can change this in your theme config', 'http://powman.org']


# About
about_info:
    name: "Sahil Ahuja"
    bio: "Typing Monkey"
    avatar: "/images/sahil_dojo420.png"

# Comment
# e.g disqus: seansun
disqus: sahil-cc
duoshuo: 

# Analytics
google_analytics: UA-87967706-1
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
